linters:
  disable-all: true
  enable:
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - scopelint
    - goimports
    - errcheck
    - lll

linters-settings:
  govet:
    check-shadowing: true
    check-unreacheable: true
    check-rangeloops: true
    check-copylocks: true
